src/Entity/Pdi.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PdiRepository")
 */
class Pdi
{

    public function __construct(int $order = -1){
        $this->client_name = "";
        $this->format = '1x1';
        $this->is_depot = false;
        $this->is_reex = false;
        $this->ordre = $order;
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $client_name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_depot;



    /**
     * @ORM\Column(type="boolean")
     */
    private $is_reex;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Tournee", inversedBy="pdis")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tournee_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Libelle", inversedBy="pdis", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $libelle_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $ordre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $format;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getClientName(): ?string
    {
        return $this->client_name;
    }

    public function setClientName(string $client_name): self
    {
        $this->client_name = $client_name;

        return $this;
    }

    public function getIsDepot(): ?bool
    {
        return $this->is_depot;
    }

    public function setIsDepot(bool $is_depot): self
    {
        $this->is_depot = $is_depot;

        return $this;
    }

    public function getIsReex(): ?bool
    {
        return $this->is_reex;
    }

    public function setIsReex(bool $is_reex): self
    {
        $this->is_reex = $is_reex;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getTourneeId(): ?Tournee
    {
        return $this->tournee_id;
    }

    public function setTourneeId(?Tournee $tournee_id): self
    {
        $this->tournee_id = $tournee_id;

        return $this;
    }

    public function getLibelleId(): ?Libelle
    {
        return $this->libelle_id;
    }

    public function setLibelleId(?Libelle $libelle_id): self
    {
        $this->libelle_id = $libelle_id;

        return $this;
    }

    public function getOrdre(): ?int
    {
        return $this->ordre;
    }

    public function setOrdre(int $ordre): self
    {
        $this->ordre = $ordre;

        return $this;
    }

    public function getFormat(): ?string
    {
        return $this->format;
    }

    public function setFormat(string $format): self
    {
        $this->format = $format;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Libelle;
use App\Entity\Pdi;
use App\Entity\Tournee;
use App\Entity\Ville;
use App\Form\PdiFormType;
use App\Repository\PdiRepository;
use App\Repository\TourneeRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/main", name="main")
     * @Route("/", name="root")
     */
    public function index(TourneeRepository $repo)
    {
        //ICI possibilité d'appliquer un filtre sur les tournées affichées en fonction des droits de l'utilisateur
        $tournees = $repo->findAll();
        return $this->render('main/index.html.twig', [
            'tournees' => $tournees,
        ]);
    }

    /**
     * @Route("/tournee/new", name="tournee_new")
     */
    public function newTournee(Request $request, ObjectManager $manager){
        
        $tournee = new Tournee();
        
        $form = $this->createFormBuilder($tournee)
            ->add('name', TextType::class, ['label' => 'Nom de la tournée'])
            ->getForm()
        ;
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $tournee->setCreatedAt(new \DateTime());
            $tournee->setUpdatedAt(new \DateTime());

            $manager->persist($tournee);
            $manager->flush();

            return $this->redirectToRoute("tournee_show", ['id' => $tournee->getId()]);
        }

        return $this->render('main/newTournee.html.twig', [
            'formTournee' => $form->createView(),
        ]);
        
    }

    /**
     * @Route("/tournee/delete/{id}", name="tournee_delete")
     */
    public function deleteTournee(Tournee $tournee, ObjectManager $manager){
        if($tournee != null){
            $manager->remove($tournee);
            $manager->flush();
        }
        return $this->redirectToRoute("main");
    }

    /**
     * @Route("/tournee/{id}", name="tournee_show")
     */
    public function tournee(Tournee $tournee){
        return $this->render('main/show.html.twig',[
            'tournee' => $tournee,
        ]);
    }

    

    /**
     * @Route("/tournee/{tournee}/pdi/new/{order}", name="pdi_new")
     * @Route("/tournee/{tournee}/pdi/{pdi}", name="pdi_edit")
     */
    public function pdi(Tournee $tournee, Pdi $pdi = null, int $order = -1, Request $request, ObjectManager $manager){
        $edit = true;
        if(!$pdi){
            if($order > -1){
                //Si un ordre est donné (on ajoute le pdi au milieu de la tournée)
                //alors il va falloir décaler tous les autres pour insérer celui-là
                $repo = $this->getDoctrine()->getRepository(Pdi::class);
                $pdisAModifier = $repo->findAllOrderGreaterThanDesc($order, $tournee->getId());
                foreach($pdisAModifier as $pdiAModifier){
                    $pdiAModifier->setOrdre($pdiAModifier->getOrdre() + 1);
                    $manager->persist($pdiAModifier);
                }                
            }
            else{
                $order = -1;
            }
            $pdi = new Pdi();
            $pdi->setTourneeId($tournee);
            $pdi->setOrdre($order);

            $ville = new Ville();

            $libelle = new Libelle();
            $libelle->setVilleId($ville);

            $pdi->setLibelleId($libelle);

            $edit = false;
        }
        
        $form = $this->createForm(PdiFormType::class, $pdi, [
            'edit' => $edit,
            ]);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            //Vérification de l'existence de la ville et de la rue dans la base de donnée
            //afin d'éviter de créer des doublons
            $allVilles = $this->getDoctrine()->getRepository(Ville::class)->findAll();
            $allLibelles = $this->getDoctrine()->getRepository(Libelle::class)->findAll();

            $nVille = false;
            $nLibelle = false;
            foreach($allVilles as $v){
                if( //On vérifie si une ville du même nom et même code postal existe deja dans la base de données
                $pdi->getLibelleId()->getVilleId()->getName() == $v->getName() 
                    && 
                $pdi->getLibelleId()->getVilleId()->getPostalCode() == $v->getPostalCode()){
                    $pdi->getLibelleId()->setVilleId($v);

                    foreach($allLibelles as $l){ //Si la ville existe deja, on vérifie si un libelle portant de le même nom n'existe pas deja.
                        if($pdi->getLibelleId()->getName() == $l->getName() && $pdi->getLibelleId()->getVilleId() == $l->getVilleId()){
                            $pdi->setLibelleId($l);
                            $nLibelle = true;
                        break;
                        }
                    }
                    $nVille = true;
                break;
                }
            }
            switch(false){
                case $nVille:
                    $pdi->getLibelleId()->getVilleId()->setCreatedAt(new \DateTime());
                    $pdi->getLibelleId()->getVilleId()->setUpdatedAt(new \DateTime());
                case $nLibelle:
                    $pdi->getLibelleId()->setCreatedAt(new \DateTime());
                    $pdi->getLibelleId()->setUpdatedAt(new \DateTime());
                default:
            }
            if(!$pdi->getId()){
                $pdi->setCreatedAt(new \DateTime());
            }
            $pdi->setUpdatedAt(new \DateTime());


            $manager->persist($pdi);
            $manager->flush();

            return $this->redirectToRoute("tournee_show", ['id' => $pdi->getTourneeId()->getId()]);
        }

        return $this->render('main/editPdi.html.twig', [
            'pdiNum' => $pdi->getNumero(),
            'pdiLibelle' => $pdi->getLibelleId(),
            'formPdi' => $form->createView(),
            'editMode' => $pdi->getId() !== null,
        ]);
    }

    /**
     * @Route("/tournee/{tournee}/pdi/{pdi}/delete", name="pdi_delete")
     */
    public function deletePdi(Pdi $pdi, ObjectManager $manager){
        //Attention, à la suppression d'un pdi, l'ordre des suivant doit être décrémenté, sinon ça laisse un trou dans l'ordre
        if($pdi != null){
            $manager->remove($pdi);

            $repo = $this->getDoctrine()->getRepository(Pdi::class);
                $pdisAModifier = $repo->findAllOrderGreaterThanDesc($pdi->getOrdre(), $pdi->getTourneeId()->getId());
                foreach($pdisAModifier as $pdiAModifier){
                    $pdiAModifier->setOrdre($pdiAModifier->getOrdre() - 1);
                    $manager->persist($pdiAModifier);
                } 


            $manager->flush(); 
        }
        return $this->redirectToRoute("tournee_show", ['id' => $pdi->getTourneeId()->getId()]);
    }

    /**
     * @Route("/dump/tournee/{id}", name="dump_tournee")
     */
    function dumpQuery(Tournee $tournee){
        //Tests des requêtes
        $doctrine = $this->getDoctrine();
        $doctrineConnection = $doctrine->getConnection();
        $stack = new \Doctrine\DBAL\Logging\DebugStack();
        $doctrineConnection->getConfiguration()->setSQLLogger($stack);
        $em = $doctrine->getManager();

        $pdiRepo = $em->getRepository(Pdi::class);

        $pdis = $pdiRepo->findByOrder(4, $tournee->getId());
        $pdis = $pdiRepo->findTopOrder($tournee->getId());
        $pdis = $pdiRepo->findAllOrderGreaterThanDesc(3, $tournee->getId());

        return $this->render('main/dump.html.twig',[
            'stack' => $stack,
        ]);
    }
}

templates/main/dump.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <div class="jumbotron">
        <h1>dump de requêtes</h1>
        {% for query in stack.queries %}
            <div>
                <p>{{query['sql']}}</p>
                <p>parameters :
                    <ul>
                        {% for param in query.params %}
                            <li>{{param}}</li>
                        {% endfor %}
                    </ul>
                </p>
            </div>
            
        {% endfor %}
    </div>

{% endblock %}

templates/main/editPdi.html.twig
{% extends 'base.html.twig' %}


{% block body %}

<!--
    <h1>Edition d'un point de distribution.</h1>

    Affiche les détails spécifiques à un point de distribution

    <ul>
        <li>Un formulaire permettra d'ajouter ou modifier les informations liées au pdi.</li>
    </ul>

-->
    <div class="jumbotron">
        <h1>{{pdiNum}} {{pdiLibelle}} <small>{{pdiLibelle.VilleId.PostalCode}} {{pdiLibelle.VilleId.Name}}</small></h1>
        {{form_start(formPdi)}}
            {{form_widget(formPdi)}}
            <button type="submit" class="btn btn-primary">
                {% if editMode %}
                    Mettre à jour
                {% else %}
                    Ajouter
                {% endif %}
            </button>
        {{form_end(formPdi)}}
    </div>
    
    

{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}

<!--
    <h1>AFFICHAGE DE LA LISTE DES TOURNEES</h1>

    Affiche la liste de toutes les tournées.

    <ul>
        <li>Un boutton permettra de supprimer une tournée.</li>
        <li>Un autre permettra d'en ajouter une nouvelle.</li>
        <li>Cliquer sur une tournée enverra sur la page de visualisation des pdis de celle-ci.</li>
    </ul>
-->
<div class="jumbotron">
    <h1>Liste des tournées.</h1>
    <p>
        <a href="{{ path('tournee_new') }}" class="btn btn-primary btn-sm">Nouvelle tournée</a>
    </p>
    
    <table class="table table-hover table-striped table-primary">
        {% for tournee in tournees %}
            <tr style="cursor: pointer;" onclick="window.location='{{ path('tournee_show', {'id': tournee.id}) }}';">
                <td>{{tournee.name}}</td>
                <td>Dernière modification le {{ tournee.createdAt | date('d/m/Y à H:m') }}</td>
                <!--<td><a href="{{ path('tournee_delete', {'id': tournee.id}) }}">X</a></td>-->
            </tr>
        {% endfor %}
    </table>
</div>
    

{% endblock %}

templates/main/newTournee.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <div class="jumbotron">
        <h1>Nouvelle tournée</h1>
        {{form_start(formTournee)}}
            {{form_widget(formTournee)}}
            <button type="submit" class="btn btn-primary">
                Ajouter
            </button>
        {{form_end(formTournee)}}
    </div>

{% endblock %}

templates/main/show.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<!--
    Affiche des pdis d'une tournée spécifique

    <ul>
        <li>Un boutton permettra de supprimer un pdi.</li>
        <li>Un autre permettra d'en ajouter un nouveau.</li>
        <li>Il faudra pouvoir les déplacer.</li>
        <li>Cliquer sur un pdi nous enverra sur une page pour éventuellement le modifier.</li>
    </ul>

-->

<div class="jumbotron">
    <h1>Tournee {{ tournee.name }}</h1>
    <p>
        <a href="{{ path('pdi_new', {'tournee' : tournee.id, 'order' : 0}) }}" class="btn btn-primary btn-sm">Nouveau PDI</a>
    </p>
    <table class="table table-hover table-striped table-primary">
        <tr><th>numéro</th><th>rue</th><th>nom</th><th>options</th></tr>
        {% for pdi in tournee.pdis %}
            <tr style="cursor: pointer;" onclick="window.location='{{ path('pdi_edit', {'tournee' : tournee.id, 'pdi': pdi.id}) }}';">
                <td>{{pdi.numero}}</td>
                <td>{{pdi.libelleid.name}}</td>
                <td>{{pdi.clientName}}</td>
                <td><a href="{{ path('pdi_new', {'tournee' : tournee.id, 'order' : pdi.ordre + 1 }) }}">Ajouter en dessous</a>    <a href="{{ path('pdi_delete', {'tournee' : tournee.id, 'pdi': pdi.id}) }}">X</a></td>
            </tr>
        {% endfor %}
    </table>
</div>

    

{% endblock %}